live_config_reload = true

# [["keyboard.bindings"]]
# action = "CreateNewWindow"
# key = "N"
# mods = "Command"
#
# [["keyboard.bindings"]]
# chars = """\u001B:w"""
# key = "S"
# mods = "Command"

[font]
# AppleFontSmoothing = true
size = 22.0

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1 

[window.padding]
x = 20
y = 20
